version: '2'
services:
  frontend:
    image: node
    links:
      - mongo
    volumes:
      - ./frontend/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon node-gyp; nodemon -e js,ejs index.js'
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
    - ./.mongo/data:/data/db
    restart: always